### **Building Bidirectional LSTM Model**

A **Bidirectional LSTM (BiLSTM)** is an extension of standard Long Short-Term Memory networks that processes sequential data in both forward and backward directions simultaneously

In [5]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Bidirectional
import numpy as np

#### **1. Data Preparation**

In [2]:
def create_dataset(sequence, n_steps):
    X, y = [], []

    for i in range(len(sequence)):
        end_ix = i + n_steps

        if end_ix >= len(sequence):
            break

        seq_x = sequence[i:end_ix]
        seq_y = sequence[end_ix]

        X.append(seq_x)
        y.append(seq_y)

    return np.array(X), np.array(y)


# How to use

#Case 1:
'''
data = [10, 20, 30, 40, 50, 60, 70, 80, 90]

n_steps = 3

X, y = create_dataset(data, n_steps)
'''

# Case 2:
'''
# Stock Price Forecasting
close_prices = [
    100, 102, 105, 107, 110,
    108, 112, 115, 118, 120
]

n_steps = 5

X, y = create_dataset(close_prices, n_steps)
'''

'\n# Stock Price Forecasting\nclose_prices = [\n    100, 102, 105, 107, 110,\n    108, 112, 115, 118, 120\n]\n\nn_steps = 5\n\nX, y = create_dataset(close_prices, n_steps)\n'

In [3]:
# define input sequence
data = [10, 20, 30, 40, 50, 60, 70, 80, 90]

# choose a number of time steps
n_steps = 3

# split into samples
X, y = create_dataset(data, n_steps)

print(X)
print(y)

[[10 20 30]
 [20 30 40]
 [30 40 50]
 [40 50 60]
 [50 60 70]
 [60 70 80]]
[40 50 60 70 80 90]


#### **2. Prepare Data for LSTM**

LSTM expects input shape: **(samples, timesteps, features)**

In [4]:
# reshape from [samples, timesteps] into [samples, timesteps, features]
n_features = 1
print("Before reshape:", X.shape)

X = X.reshape((X.shape[0], X.shape[1], 1))

print("After reshape:", X.shape)

Before reshape: (6, 3)
After reshape: (6, 3, 1)


#### **3. Prepare Bidirectional LSTM**

In [7]:
model = Sequential()
model.add(Bidirectional(LSTM(50, activation='relu'), input_shape=(n_steps, 1)))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')

#### **4. Train Model**

In [8]:
model.fit(X, y, epochs=200, verbose=1)

Epoch 1/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 922ms/step - loss: 4057.5974
Epoch 2/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 4026.8953
Epoch 3/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 3995.5227
Epoch 4/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 3963.4016
Epoch 5/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 3930.4543
Epoch 6/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 3896.5823
Epoch 7/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 3861.6934
Epoch 8/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 3825.8040
Epoch 9/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 3788.6584
Epoch 10/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 3750.0930
Epoch 11/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 3709.9553
Epoch 12/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 3668.0862
Epoch 13/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 3624.3167
Epoch 14/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 3578.4592
Epoch 15/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 2

#### **5. Model Prediction**

In [9]:
x_input = np.array([70,80,90])

x_input = x_input.reshape((1, n_steps, 1))

prediction = model.predict(x_input)

print(prediction)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step
[[100.89764]]
