### **Building an LSTM Model**

In [1]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense
import numpy as np

I0000 00:00:1790403206.043495   54710 port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
I0000 00:00:1790403206.043889   54710 cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
I0000 00:00:1790403206.070237   54710 cpu_feature_guard.cc:227] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI AVX512_BF16 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
I0000 00:00:1790403206.835951   54710 port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONE

#### **1. Data Preparation**

In [2]:
def create_dataset(sequence, n_steps):
    X, y = [], []

    for i in range(len(sequence)):
        end_ix = i + n_steps

        if end_ix >= len(sequence):
            break

        seq_x = sequence[i:end_ix]
        seq_y = sequence[end_ix]

        X.append(seq_x)
        y.append(seq_y)

    return np.array(X), np.array(y)


# How to use

#Case 1:
'''
data = [10, 20, 30, 40, 50, 60, 70, 80, 90]

n_steps = 3

X, y = create_dataset(data, n_steps)
'''

# Case 2:
'''
# Stock Price Forecasting
close_prices = [
    100, 102, 105, 107, 110,
    108, 112, 115, 118, 120
]

n_steps = 5

X, y = create_dataset(close_prices, n_steps)
'''

'\n# Stock Price Forecasting\nclose_prices = [\n    100, 102, 105, 107, 110,\n    108, 112, 115, 118, 120\n]\n\nn_steps = 5\n\nX, y = create_dataset(close_prices, n_steps)\n'

In [3]:
# define input sequence
data = [10, 20, 30, 40, 50, 60, 70, 80, 90]

# choose a number of time steps
n_steps = 3

# split into samples
X, y = create_dataset(data, n_steps)

print(X)
print(y)

[[10 20 30]
 [20 30 40]
 [30 40 50]
 [40 50 60]
 [50 60 70]
 [60 70 80]]
[40 50 60 70 80 90]


#### **2. Prepare Data for LSTM**

LSTM expects input shape: **(samples, timesteps, features)**

In [4]:
# reshape from [samples, timesteps] into [samples, timesteps, features]
n_features = 1
print("Before reshape:", X.shape)

X = X.reshape((X.shape[0], X.shape[1], 1))

print("After reshape:", X.shape)

Before reshape: (6, 3)
After reshape: (6, 3, 1)


#### **3. Prepare Vanilla LSTM**

In [6]:
## Define Model
model = Sequential()
model.add(LSTM(50, activation='relu', input_shape=(n_steps, n_features)))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')

#### **4. Train Model**

In [7]:
model.fit(X, y, epochs=200, verbose=1)

Epoch 1/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 608ms/step - loss: 5393.3716
Epoch 2/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 5269.6655
Epoch 3/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 5146.4233
Epoch 4/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 5023.4727
Epoch 5/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 4900.3794
Epoch 6/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 4776.4922
Epoch 7/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 4650.6089
Epoch 8/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 4521.7622
Epoch 9/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 4392.0366
Epoch 10/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 4261.6328
Epoch 11/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 4130.7461
Epoch 12/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 3999.9502
Epoch 13/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 3869.7073
Epoch 14/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 3740.3738
Epoch 15/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 2

#### **5. Model Prediction**

In [8]:
x_input = np.array([70,80,90])

x_input = x_input.reshape((1, n_steps, 1))

prediction = model.predict(x_input)

print(prediction)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step
[[102.91061]]
