### **Building an LSTM Model**

In [3]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense
import numpy as np

#### **1. Data Preparation**

In [11]:
def create_dataset(sequence, n_steps):
    X, y = [], []

    for i in range(len(sequence)):
        end_ix = i + n_steps

        if end_ix >= len(sequence):
            break

        seq_x = sequence[i:end_ix]
        seq_y = sequence[end_ix]

        X.append(seq_x)
        y.append(seq_y)

    return np.array(X), np.array(y)


# How to use

#Case 1:
'''
data = [10, 20, 30, 40, 50, 60, 70, 80, 90]

n_steps = 3

X, y = create_dataset(data, n_steps)
'''

# Case 2:
'''
# Stock Price Forecasting
close_prices = [
    100, 102, 105, 107, 110,
    108, 112, 115, 118, 120
]

n_steps = 5

X, y = create_dataset(close_prices, n_steps)
'''

'\n# Stock Price Forecasting\nclose_prices = [\n    100, 102, 105, 107, 110,\n    108, 112, 115, 118, 120\n]\n\nn_steps = 5\n\nX, y = create_dataset(close_prices, n_steps)\n'

In [15]:
# define input sequence
data = [10, 20, 30, 40, 50, 60, 70, 80, 90]

# choose a number of time steps
n_steps = 3

# split into samples
X, y = create_dataset(data, n_steps)

print(X)
print(y)

[[10 20 30]
 [20 30 40]
 [30 40 50]
 [40 50 60]
 [50 60 70]
 [60 70 80]]
[40 50 60 70 80 90]


#### **2. Prepare Data for LSTM**

LSTM expects input shape: **(samples, timesteps, features)**

In [16]:
# reshape from [samples, timesteps] into [samples, timesteps, features]
n_features = 1
print("Before reshape:", X.shape)

X = X.reshape((X.shape[0], X.shape[1], 1))

print("After reshape:", X.shape)

Before reshape: (6, 3)
After reshape: (6, 3, 1)


#### **3. Prepare Vanilla LSTM**

In [ ]:
## Define Model
model = Sequential()
model.add(LSTM(50, activation='relu', input_shape=(n_steps, n_features)))
model.add(Dense(1))
model.compile(optmizer='adam', loss='mse')